Webdriver
AleksandrVoyteshenko/Automation pull request #2
Opened 2020-12-08 10:33 UTC by AleksandrVoyteshenko

tasks section webdriver

2020-12-08 11:39 UTC, nitrogen16 requested changes
At first clean code comments

2020-12-08 11:39 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/GoogleCalculator.java
> +public class GoogleCalculator {
GoogleCalculatorTest

2020-12-08 11:39 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/GoogleCloudResultSearch.java
> +public class GoogleCloudResultSearch {
GoogleCloudResultSearchPage

2020-12-08 11:39 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/PageGeneratingRandomMail.java
> +public class PageGeneratingRandomMail {
GeneratingRandomMailPage

2020-12-08 11:39 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hurt_me_plenty/GoogleCalculator.java
> +public class GoogleCalculator {
GoogleCalculatorPage

2020-12-08 11:39 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hurt_me_plenty/GoogleCloudHomePage.java
> +package webdriver.pages.hurt_me_plenty;
package naming!

2020-12-08 11:39 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hurt_me_plenty/GoogleCloudResultSearch.java
> +public class GoogleCloudResultSearch {
GoogleCloudResultSearchPage

2020-12-08 11:39 UTC, nitrogen16 commented on src/test/java/webdriver/test/ControlcTestTaskBringItOn.java
> +public class ControlcTestTaskBringItOn extends BaseTest {
ControlcTaskBringItOnTest
Test is written in the end of class name

2020-12-08 11:39 UTC, nitrogen16 commented on src/test/java/webdriver/test/TestTaskHardcore.java
> +public class TestTaskHardcore extends BaseTest {
TaskHardcoreTest

2020-12-08 11:43 UTC, AleksandrVoyteshenko commented on src/test/java/webdriver/test/TestTaskHardcore.java
> +public class TestTaskHardcore extends BaseTest {
fixed

2020-12-08 11:44 UTC, AleksandrVoyteshenko commented on src/test/java/webdriver/test/ControlcTestTaskBringItOn.java
> +public class ControlcTestTaskBringItOn extends BaseTest {
fixed

2020-12-08 11:45 UTC, AleksandrVoyteshenko commented on src/test/java/webdriver/pages/hurt_me_plenty/GoogleCloudResultSearch.java
> +public class GoogleCloudResultSearch {
fixed

2020-12-08 11:45 UTC, AleksandrVoyteshenko commented on src/test/java/webdriver/pages/hardcore/PageGeneratingRandomMail.java
> +public class PageGeneratingRandomMail {
fixed

2020-12-08 11:46 UTC, AleksandrVoyteshenko commented on src/test/java/webdriver/pages/hurt_me_plenty/GoogleCalculator.java
> +public class GoogleCalculator {
fixed

2020-12-08 11:52 UTC, AleksandrVoyteshenko commented on src/test/java/webdriver/pages/hardcore/GoogleCloudResultSearch.java
> +public class GoogleCloudResultSearch {
fixed

2020-12-08 11:52 UTC, AleksandrVoyteshenko commented on src/test/java/webdriver/pages/hardcore/GoogleCalculator.java
> +public class GoogleCalculator {
fixed

2020-12-08 11:53 UTC, AleksandrVoyteshenko commented on src/test/java/webdriver/pages/hardcore/GoogleCloudResultSearch.java
> +public class GoogleCloudResultSearch {
fixed

2020-12-08 13:31 UTC, nitrogen16 requested changes
Thoroughly comment by comment fix your framework approach.

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/i_can_win/HelloWebDriver.java
> +public class HelloWebDriver {
If HelloWebDriver is test, why it's locted in this folder 'pages'?

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/test/BaseTest.java
> +        if (null == driver) {
More or less it's ok. But it's better to create a separate class for Driver and calls a webDriver instance kind of Driver.getWebDriverInstance(). So, you'll creation webdriver in one place.

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/test/BaseTest.java
> +    public static WebDriver quitBrowser(){
Why it's not void. Why do you return WebDriver?

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/test/BaseTest.java
> +        return driver;
code smells

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/test/ControlcTaskBringItOnTest.java
> +        String newTtile = new ControlcHomePage(driver).openPage().dataEntryWithParameters().titleNewPaste();
newTitle

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/test/ControlcTaskBringItOnTest.java
> +public class ControlcTaskBringItOnTest extends BaseTest {
Typo.
ControlcTaskBringItOnTest -> ControlTaskBringItOnTest or what is better approprate

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/test/TaskHardcoreTest.java
> +    private String search = "Google Cloud Platform Pricing Calculator";
Move to test method.
As I understand, it's a test data.

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/test/TaskHurtMyPlantyTest.java
> +        String resultSumOfManualTesting = "Total Estimated Cost: USD 1,082.77 per 1 month";
Add a space after test data. It's not readable.

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hurt_me_plenty/ResultAddVMPage.java
> +        classVM = driver.findElement(By.xpath(resultFieldVMClass)).getText();
More no than yes. I would suggest to divide this method into several methods.

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hurt_me_plenty/GoogleCloudHomePage.java
> +    private String urlHomePage = "https://cloud.google.com";
Is it okay to store test urls in page class and use them?
What if tested env has this url as "https://cloud.google.com/qa-envirenment"?

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hurt_me_plenty/GoogleCloudHomePage.java
> +        driver.get(urlHomePage);
hard coded test data

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hurt_me_plenty/GoogleCalculatorPage.java
> +        (new WebDriverWait(driver, Duration.ofSeconds(TIME_OUT_SECOND))).until(ExpectedConditions.elementToBeClickable(By.xpath(valueSeries))).click();
The same waiter in several places. In fact, code is duplicated.
Suggest to create a separate wait method which will wait any webelement you pass

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hurt_me_plenty/GoogleCalculatorPage.java
> +    private String numberGPU = "//*[@id = 'select_value_label_391']";
select_value_label_391
I do not like 391. It can change in length of time. The same comment for all such xpathes

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/GoogleCloudHomePage.java
> +    private String URL_HOME_PAGE = "https://cloud.google.com";
Again. You store test data in page class.

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/GoogleCloudHomePage.java
> +        driver.get(URL_HOME_PAGE);
"https://cloud.google.com" changes to "https://cloud.platform.google.com"
Will it work?

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/GoogleCalculatorPage.java
> +        new WebDriverWait(driver, Duration.ofSeconds(TIME_OUT_SECOND)).until(ExpectedConditions.visibilityOfElementLocated(By.id(idChildrFrame)));
Create a separate waiter. The same code repeats again and again in code.
And moreover it's hard to read such long scenarios strings

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/GoogleCalculatorPage.java
> +        driver.switchTo().frame(0);
Create a separate method for switching between frames.
0 is a magic value in this case.

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/GoogleCalculatorPage.java
> +    static int TIME_OUT_SECOND = 30;
Hmmm... Why this variable?

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/bring_it_on/ControlcResultPage.java
> +        driver.switchTo().frame(frame);
It's better to create a separate method for switching to other frame. Why we switch to other frame? It's incapsulated in your method

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/bring_it_on/ControlcHomePage.java
> +    public static String textPaste = "git config --global user.name \"New Sheriff in Town\"\n" +
Test data in page class. Bad practice. Test data should be in tests.

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/bring_it_on/ControlcHomePage.java
> +    private String NewPaste = "input_text";
naming of variables

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/bring_it_on/ControlcHomePage.java
> +    private String URL = "https://controlc.com/";
and again url in page

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/bring_it_on/ControlcHomePage.java
> +    private String valueCodeHighlighting = "//option[@value = '1']";
Not sure whether this xpath is stable enough in a length of time.

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/bring_it_on/ControlcHomePage.java
> +    public static String titleName = "how to gain dominance among developers";
Why static?

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/bring_it_on/ControlcHomePage.java
> +    public ControlcHomePage(WebDriver driver) {
Here and for all pages.
Create a parent page, make inherirance, move all common methods to it.

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/bring_it_on/ControlcHomePage.java
> +    protected WebDriver driver;
Code duplicated for all page classes. In each page class you create a webDriver. Use inheritance. Create a parent page.

2020-12-08 13:31 UTC, nitrogen16 commented on src/test/java/webdriver/pages/bring_it_on/ControlcHomePage.java
> +        driver.findElement(By.id(NewPaste)).sendKeys(textPaste);
Code smells. Hard-coded test data in page class.

2020-12-09 05:56 UTC, AleksandrVoyteshenko commented on src/test/java/webdriver/test/BaseTest.java
> +    public static WebDriver quitBrowser(){
made a method with void

2020-12-09 05:57 UTC, AleksandrVoyteshenko commented on src/test/java/webdriver/test/BaseTest.java
> +        return driver;
fixed

2020-12-09 05:58 UTC, AleksandrVoyteshenko commented on src/test/java/webdriver/test/ControlcTaskBringItOnTest.java
> +        String newTtile = new ControlcHomePage(driver).openPage().dataEntryWithParameters().titleNewPaste();
fixed

2020-12-09 06:04 UTC, AleksandrVoyteshenko commented on src/test/java/webdriver/pages/bring_it_on/ControlcHomePage.java
> +    private String valueCodeHighlighting = "//option[@value = '1']";
This field has the name of "Enable code highlighting?". It has two value: No (value 0) and Yes (value 1). So I think xpath will not change.

2020-12-09 06:10 UTC, AleksandrVoyteshenko commented on src/test/java/webdriver/pages/bring_it_on/ControlcHomePage.java
> +    public static String titleName = "how to gain dominance among developers";
I moved the variables to the test class as they are test data. And passed parameters with these variables to the method

2020-12-09 14:33 UTC, nitrogen16 requested changes
Fix ALL comments. Including legacy

2020-12-09 14:33 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/GeneratingRandomMailPage.java
> +    static String windowMailPage;
static variables
1) Why static?
2) For what are they?

2020-12-09 14:33 UTC, nitrogen16 commented on src/test/java/webdriver/pages/ParentPage.java
> +    public String readFieldText(String locator) {
readFieldText -> getFieldText

2020-12-09 14:33 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/GoogleCloudHomePage.java
> +        buttonSearch.sendKeys(search, Keys.ENTER);
Split into several actions: click button, enter text, click search
//input[@aria-label='Search']

2020-12-09 14:33 UTC, nitrogen16 commented on src/test/java/webdriver/pages/ParentPage.java
> +    public ParentPage clickElementToBeClickable(String locator) {
What is the sense to join methods?
Separately wait element, after that click on it.

2020-12-09 14:33 UTC, nitrogen16 commented on src/test/java/webdriver/pages/ParentPage.java
> +    public ParentPage clickOfElementLocated(String locator) {
The same as comment above

2020-12-09 14:33 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/GoogleCalculatorPage.java
> +        openDropdown(machineClass).clickField(valueVM);
hard coded values
Code smells
Where is the test data?

2020-12-09 14:33 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/GoogleCalculatorPage.java
> +        new WebDriverWait(driver, Duration.ofSeconds(TIME_OUT_SECOND)).until(ExpectedConditions.frameToBeAvailableAndSwitchToIt(By.id(childFrame)));
and again code is duplicated
Why not to create a separate method for it?

2020-12-09 14:33 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/GoogleCalculatorPage.java
> +        inputText(fieldAddMail, amailAdress);
That's absolutely unappropriate.
Value on one page. It's static... You retrieve it from page... It's again a test data

2020-12-09 14:33 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hurt_me_plenty/GoogleCalculatorPage.java
> +    private String numberGPU = "//*[@id = 'select_value_label_391']";
and what finally?

2020-12-09 14:33 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/GoogleCloudHomePage.java
> +    public ParentPage openPage(String URL) {
What is OOP? Why are you overriding?

2020-12-09 14:46 UTC, nitrogen16 commented on src/test/java/webdriver/pages/bring_it_on/ControlcHomePage.java
> +        openDropdown(codeHighlighting);
create method selectValueFromDropdown

2020-12-09 15:06 UTC, nitrogen16 commented on src/test/java/webdriver/pages/ParentPage.java
> +        driver.manage().window().maximize();
Move to driver initialization place.

2020-12-24 09:41 UTC, nitrogen16 approved these changes
Fix comments and then merge

2020-12-24 09:41 UTC, nitrogen16 commented on src/test/java/webdriver/pages/bring_it_on/ControlcHomePage.java
> +    private String lookDataPaste = "//b[text() = 'Click here']";
what is it? lookDataPaste

2020-12-24 09:41 UTC, nitrogen16 commented on src/test/java/webdriver/pages/bring_it_on/ControlcHomePage.java
> +    private String dropdownCodeHighlighting = "//div[span[contains(text(), 'Enable code highlighting?')]]//following-sibling::div/select";
Here and down all element types at the end of names. 
dropdownCodeHighlighting -> codeHighlightingDropdown

2020-12-24 09:41 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hardcore/GeneratingRandomMailPage.java
> +    private String valueNumberMessage = "1 mail";
hard-core

2020-12-24 09:41 UTC, nitrogen16 commented on src/test/java/webdriver/pages/hurt_me_plenty/ResultAddVMPage.java
> +    private String resultFieldVMClass = "//md-list-item[2]";
Is it possilble to tie xpath with dropdown name in order not to use 2, 3, 4, 5 indexes?

2020-12-24 11:21 UTC, merged